config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'static_pages#home'
  get 'home', to: 'static_pages#home'
  get 'about', to: 'static_pages#about'

  get 'signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'sessions', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'users', to: 'users#create'
  get 'users/:id', to: 'users#show', as: 'user'
  get 'users', to: 'users#index'
  get 'users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch 'users/:id', to: 'users#update'
  delete 'users/:id', to: 'users#destroy', as: 'destroy_user'

  resources :journals, only: [:create]
  resources :password_resets

end

app/models/journal.rb
class Journal < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	# validates(:name, presence: true)
	validates :name, presence: true, length: { maximum: 50 }
	validates :email, presence: true, uniqueness: true,
		format: { with: VALID_EMAIL_REGEX }

	has_secure_password

	has_many :journals, dependent: :destroy
	# has_one :profiles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	include SessionsHelper

	def do_login(user)
		session[:user_id] = user.id unless session[:user_id]
	end

	# def current_user
	# 	@current_user = User.find_by(id: session[:user_id])
	# end

	def logged_in_user
		redirect_to login_url, 
			# alert: 'Please login dulu bro' unless session[:user_id]
			alert: 'Please login dulu bro' unless current_user
	end

	def correct_user
		# byebug
		redirect_to root_url,
			# alert: 'Gak boleh ke sini ya bro' unless params[:id] == session[:user_id]
			alert: 'Gak boleh ke sini ya bro' unless params[:id].to_i == session[:user_id]
	end

	def admin_user

	end

end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
	before_action :logged_in_user
	def create
		# render json: params and return
		@journal = current_user.journals.
			# build(params[:journal])
			build(journal_params)

		if @journal.save
			# redirect_to root_path, notice: 'Journal created!'
			render partial: 'journal'

			# respond_to do |format|
			# 	format.js
			# 	format.json { render json: @journal }
			# 	format.xml { render xml: @journal }
			# end
		else
			# render 'static_pages/home', alert: 'Something wrong'
			redirect_to root_url, alert: 'Something wrong'
		end
	end

	private

	def journal_params
		params.require(:journal).permit(:title, :content)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:email])

		if user && user.authenticate(params[:password])
			do_login(user)
			redirect_to user_url(user), notice: 'Login Successfully'
		else
			redirect_to login_url, alert: 'Invalid Email / Password'
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url, notice: 'Logged Out Successfully'
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@journal = Journal.new
  	@journals = current_user.journals.order(created_at: :desc) if current_user
  end

  def about
  end

  private

  def private_home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # before_action :logged_in_user, only: [:index]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  # before_action :logged_in_user, except: [:show, :index]
  # after_action
  # around_action
  
  before_action :correct_user, only: [:edit, :update]
  # before_action :admin_user, only: [:edit, :update]

  def index
    # @users = User.all
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
  	@user = User.new
  	# @user = User.new(name: 'Erric')
  end

  # def edit
  # 	@user = User.find(params[:id])
  # end

  def create

  	# render json: params and return
  	# render json: params[:user]
  	
  	# @user = User.new(params[:user])

  	# @user = User.new
  	# @user.name = params[:user][:name]
  	# @user.email = params[:user][:email]

  	@user = User.new(user_params)

  	#@user.save
    if @user.save
      do_login(@user)
      redirect_to user_url(@user), notice: 'User created!'
    else
      render :new
    end

  	# redirect_to root_path, notice: 'User created!'
    # redirect_to user_url(@user), notice: 'User created!'

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user, notice: 'User updated!'
    else
      render edit
    end
  end

  def destroy
    @user = User.find(params[:id]).destroy
    redirect_to users_url, notice: 'OK, User udah dihapus bro'
  end

  private

    def user_params
    	params.require(:user).permit(
    		:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def hello_world
		"hello erric"
	end

	def current_user
		# @current_user = @current_user || User.find_by(id: session[:user_id])
		@current_user ||= User.find_by(id: session[:user_id])
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, options = { size: 80 })
		gravatar_id = Digest::MD5::hexdigest(user.email)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: 'gravatar')
	end
	
end

app/views/journals/_journal.html.erb
<h3><%= @journal.title %></h3>
<p><%= @journal.content %></p>
Posted <%= time_ago_in_words(@journal.created_at) %> ago
<hr />

app/views/journals/create.js.erb
$('.list-journals').prepend("<%= escape_javascript(render) %>");
$('#journal_title').val();
$('#journal_content').val();

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
  ErricApp by Erric
</small>
<nav>
  <ul>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Contact", '#' %></li>
  </ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
<div class="container">
	<%= link_to "ErricApp", root_path, id: "logo" %>
	<nav>
		<ul class="nav navbar-nav pull-right">
			<li><%= link_to "Home", root_path %></li>
			<% # if session[:user_id] %>
			<% if current_user %>
				<li><%= link_to "Users", users_path %></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<!--<li><%= link_to "Profile", user_path(current_user.id) %></li>-->
						<li><%= link_to "Profile", current_user %></li>
						<li><%= link_to "Setting", edit_user_path(current_user) %></li>
						<li class="divider"></li>
						<li><%= link_to "Log out", logout_path, method: :delete %></li>
					</ul>
				</li>
			<% else %>
				<li><%= link_to "Log in", login_path %></li>
		 <% end %>
		</ul>
	</nav>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:page_title) %> | ErricApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

  <div class="container">
    <% if notice %>
      <div class="alert alert-success"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger"><%= alert %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug params if Rails.env.development? %>
  </div>

</body>
</html>

app/views/static_pages/about.html.erb
<% provide :page_title, 'About' %>
<h1>About</h1>
<p><strong>ErricApp</strong> is a blog for the adventurous mind</p>

app/views/static_pages/home.html.erb
<% provide :page_title, 'Home' %>

<% if current_user %>
	<%= form_for(@journal, remote: true) do |f| %>
		<%= f.label :title %>
		<%= f.text_field :title %>

		<%= f.label :content %>
		<%= f.text_area :content %>

		<%= f.submit 'Create Journal', class: 'btn btn-primary' %>
	<% end %>

	<h1>Last 10 Journals</h1>
	<%= render @journals %>
	<% # @journals.each do |journal| %>
		<!--<div class="list-journals">
			<h3><%= journal.title %></h3>
			<p><%= journal.content %></p>
			Posted <%= time_ago_in_words(journal.created_at) %>
			<hr />
		</div> -->
	<% # end %>
<% else %>
	<div class="center jumbotron">
		<h1>Selamat Datang ke ErricApp</h1>
		<h2>
		  This is the home page for the ErricApp application.
		</h2>
		<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
	</div>
<% end %>


	
<!-- <a href="<%= about_path %>">About</a>
<%= link_to('About', about_path) %>
<%= link_to about_path do %>
	<h1>About Loh</h1>
<% end %>
<%= number_to_currency 100000000, unit: 'IDR' %>
<%= pluralize 2, 'datum' %>
<%= date_field_tag :hello %>
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>
 
 -->

app/views/users/edit.html.erb
<% provide :page_title, 'Edit User' %>

<h1>Edit User</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">

	<% if @user.errors.any? %>	
		<div class="panel">
			<ul class="text-danger">
				<% @user.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<%= form_for(@user) do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :email %>
		<%= f.email_field :email %>
		
		<%= f.label :password %>
		<%= f.password_field :password %>

		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>

		<%= f.submit "Update User", class: 'btn btn-primary' %>
	<% end %>

	</div>
</div>

app/views/users/index.html.erb
<h1>List of Users</h1>
<%= will_paginate %>
<table class="table">
<% @users.each do |user| %>
	<tr>
		<td><%= link_to user.name, user_path(user) %></td>
		<td><%= user.email %></td>
		<% if current_user.admin? %>
			<td><%= link_to "delete 1", destroy_user_path(user.id), method: :delete, data: {confirm: "Yakin bro?"} %></td>
			<td><%= link_to "delete 2", user_path(user.id), method: :delete, data: {confirm: "Yakin bro?"} %></td>
		<% end %>
	</tr>
<% end %>
</table>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide :page_title, 'Sign up' %>

<h1>Sign Up</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">

	<% if @user.errors.any? %>	
		<div class="panel">
			<ul class="text-danger">
				<% @user.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<%= form_for(@user) do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :email %>
		<%= f.email_field :email %>
		
		<%= f.label :password %>
		<%= f.password_field :password %>

		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>

<%
=begin %>
	<%= hidden_field_tag :hidden_man %>

	<%= f.label :created_at %>
	<%= f.date_field :created_at %>

	<%= date_field_tag :some_date %>
<%
=end %>

		<%= f.submit "Create my account", class: 'btn btn-primary' %>
	<% end %>

	</div>
</div>

app/views/users/show.html.erb
<% provide :page_title, 'User Detail' %>
<!--<%= hello_world %>-->
<%= @user.name %>, <%= @user.email %>

<div class="row">
	
	<%= gravatar_for(@user) %>
</div>